version: 2
jobs:
  get_aws-cli_and_deploy:
    branches:
      only:
        - master
        - staging
    docker:
      - image: circleci/php:5.6.30-apache
    working_directory: ~/circleci/
    steps:
      - checkout
      - run:
          name: Setup AWS-CLI
          command: |
            curl -kL https://bootstrap.pypa.io/get-pip.py | python
            pip install awscli --upgrade
            aws --version
      # - run:
      #     name: Setup AWS credentials
      #     command: |
      #       mkdir -p ~/.aws
      #       printf "[default]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}\nregion = ap-northeast-1" > ~/.aws/config
      #       printf "[default]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/credentials
      #       chmod 600 ~/.aws/*
      # - deploy:
      #     name: push to S3
      #     command: |
      #         aws deploy push \
      #             --application-name aws-study-staticHTML \
      #             --s3-location s3://codedeploy-for-aws-study/circleci-2.zip \
      #             --region us-east-2
      # - deploy:
      #     name: Deploy to EC2
      #     command: |
      #         aws deploy create-deployment \
      #             --application-name aws-study-staticHTML \
      #             --s3-location bucket=codedeploy-for-aws-study,key=circleci-2.zip,bundleType=zip \
      #             --deployment-group-name aws-study-staticHTML-deploygroup \
      #             --region us-east-2
      - deploy:
          name: Deploy to EC2
          command: |
              GITHUB_REPO=`echo $CIRCLE_REPOSITORY_URL | sed -e 's/git@github.com://' | sed -e 's/.git$//' `
              aws deploy create-deployment \
                  --application-name StartByCircleCI \
                  --github-location repository=${GITHUB_REPO},commitId=${CIRCLE_SHA1} \
                  --deployment-group-name ${CIRCLE_BRANCH}-group \
